package handlers

import (
	"ticket-system/db"
	"ticket-system/models"

	"github.com/gin-gonic/gin"
)

type createTicketInput struct {
	Title       string `json:"title" binding:"required"`
	Description string `json:"description"`
}

func CreateTicket(c *gin.Context) {
	var input createTicketInput
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}

	// Grab the user_id that the Auth middleware extracted from the JWT.
	userID := c.GetUint("user_id")
	
	// Build the ticket model. The ID is generated by the database.
	ticket := models.Ticket{
		Title:       input.Title,
		Description: input.Description,
		Status:      "open", // All new tickets start as open
		UserID:      userID, // Link the ticket to the user who created it
	}

	// Save to the database.
	if err := db.DB.Create(&ticket).Error; err != nil {
		c.JSON(500, gin.H{"error": "could not create ticket"})
		return
	}

	c.JSON(201, ticket)
}

func ListTickets(c *gin.Context) {
	// Grab the user_id from the context (set by the Auth middleware).
	userID := c.GetUint("user_id")

	// Find ALL tickets that belong to this specific user.
	// Python equivalent: db.query(Ticket).filter(Ticket.user_id == user_id).all()
	var tickets []models.Ticket
	db.DB.Where("user_id = ?", userID).Find(&tickets)

	c.JSON(200, tickets)
}

func GetTicket(c *gin.Context) {
	userID := c.GetUint("user_id")
	// Get the ID from the URL path: e.g. /tickets/5 -> id is "5"
	id := c.Param("id")

	var ticket models.Ticket
	// Security check: We MUST include 'user_id = ?' in the query.
	// This prevents User A from fetching User B's ticket by guessing the ID.
	if err := db.DB.Where("id = ? AND user_id = ?", id, userID).First(&ticket).Error; err != nil {
		// If the ticket belongs to someone else, it returns 404 Not Found, 
		// acting like the ticket doesn't exist at all to prevent data leakage.
		c.JSON(404, gin.H{"error": "ticket not found"})
		return
	}

	c.JSON(200, ticket)
}

// validTransitions defines the strict state machine for ticket statuses.
// A map acts like a Python dictionary. Key = current state, Value = allowed next state.
var validTransitions = map[string]string{
	"open":        "in_progress",
	"in_progress": "closed",
}

type updateStatusInput struct {
	Status string `json:"status" binding:"required"`
}

func UpdateStatus(c *gin.Context) {
	var input updateStatusInput
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}

	userID := c.GetUint("user_id")
	id := c.Param("id")

	var ticket models.Ticket
	// Fetch the ticket AND enforce ownership.
	if err := db.DB.Where("id = ? AND user_id = ?", id, userID).First(&ticket).Error; err != nil {
		c.JSON(404, gin.H{"error": "ticket not found"})
		return
	}

	// Rule: Closed tickets are terminal and cannot be modified.
	if ticket.Status == "closed" {
		c.JSON(400, gin.H{"error": "closed ticket cannot be reopened"})
		return
	}

	// Validate the state transition.
	// 'allowed' is the required next state. 'ok' is true if the current state exists in the map.
	allowed, ok := validTransitions[ticket.Status]
	
	// If the current state isn't in the map, OR the requested state doesn't match the allowed next state:
	if !ok || allowed != input.Status {
		c.JSON(400, gin.H{
			"error": "invalid status transition",
			"hint":  "allowed: open → in_progress → closed",
		})
		return
	}

	// Execute an UPDATE query on the database.
	db.DB.Model(&ticket).Update("status", input.Status)
	// Update the local struct so the JSON response reflects the new status.
	ticket.Status = input.Status

	c.JSON(200, ticket)
}
